export const REASON_CODES = [
  "CANCELLED_BY_USER",
  "TIME_LIMIT_EXCEEDED",
  "TURN_LIMIT_EXCEEDED",
  "PROCESS_ERROR",
  "INFRA_FAILURE_EXHAUSTED",
  "AGENT_UNAVAILABLE",
  "AGENT_NOT_AUTHENTICATED",
  "REPORT_MISSING",
  "REPORT_INVALID",
  "ACTION_DENIED",
  "WRITE_OUTSIDE_SCOPE",
  "AGENT_REPORTED_FAILED",
  "AGENT_REPORTED_BLOCKED",
  "REPORTED_COMPLETED_WITH_BLOCKERS",
  "UPSTREAM_NOT_SUCCEEDED",
  "REJECTED_BY_USER",
  "RUN_CANCELLED",
] as const;

export const WARNING_CODES = [
  "DENIAL_CHECK_NOT_AVAILABLE",
  "TURN_LIMIT_NOT_APPLICABLE",
  "NO_NETWORK_ON_PLATFORM",
  "COST_NOT_REPORTED",
  "USAGE_NOT_LIVE",
  "READONLY_COMMANDS_AUTO_APPROVED",
  "AUTH_API_KEY_UNVERIFIED",
  "SCOPE_ENFORCEMENT_DETECTION_ONLY",
  "MODEL_DEFAULTED",
  "MODEL_MISMATCH",
  "UNCOMMITTED_CHANGES_EXCLUDED",
  "AGENT_CANNOT_CONFINE",
] as const;

export const DIAGNOSTIC_CODES = [
  "FILE_PARSE_ERROR",
  "SCHEMA_ERROR",
  "NO_INPUT_NODE",
  "MULTIPLE_INPUT_NODES",
  "INPUT_HAS_PREDECESSOR",
  "CYCLE",
  "DISCONNECTED_NODE",
  "APPROVAL_WITHOUT_PREDECESSOR",
  "MULTIPLE_CODE_SOURCES",
  "INVALID_LIMIT",
  "SCOPE_PATH_NOT_FOUND",
  "OPTION_NOT_APPLICABLE",
] as const;

export type ReasonCode = (typeof REASON_CODES)[number];
export type WarningCode = (typeof WARNING_CODES)[number];
export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[number];
