package com.zeko.executioncontrol.domain;

import com.zeko.sharedkernel.domain.DomainError;
import java.util.regex.Pattern;

public final class CommitMessagePolicy {
  private static final Pattern CONVENTIONAL =
      Pattern.compile("^(feat|fix|refactor|test|docs|chore|build|ci|perf|"
                      + "style|revert)(\\([^)]*\\))?: T\\d{3} .+");
  public void validate(String message) {
    if (message == null || !CONVENTIONAL.matcher(message).matches()) {
      throw DomainError.validation(
          "El commit requiere Conventional Commit e ID de task");
    }
    String lower = message.toLowerCase(java.util.Locale.ROOT);
    if (lower.contains("co-authored-by") || lower.contains("generated by") ||
        lower.contains("ai-assisted")) {
      throw DomainError.forbidden(
          "El commit no admite firmas ni coautoria de asistentes");
    }
  }
}
